/**
 * Gradle plugin that configures Magisk project properties from multiple sources.
 *
 * <p>Property resolution order (later overrides earlier):
 * <ol>
 *   <li>Gradle project properties prefixed with {@code magisk.}</li>
 *   <li>{@code config.prop} in the project root directory</li>
 *   <li>{@code flags.prop} generated by {@code build.py} in the build directory</li>
 * </ol>
 *
 * <p>Also initializes the shared {@link RANDOM} instance used by {@link Stub.kt} for
 * reproducible (CI) or secure (local) random name generation.
 */
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.provideDelegate
import java.io.File
import java.util.Properties
import java.util.Random

// Set non-zero value here to fix the random seed for reproducible builds.
// CI builds are always reproducible (seed=42).
val RAND_SEED = if (System.getenv("CI") != null) 42 else 0

/** Shared {@link Random} instance used by stub generation and other tasks. */
lateinit var RANDOM: Random

private val props = Properties()

/** Consolidated access to all Magisk build configuration properties. */
object Config {
    operator fun get(key: String): String? {
        val v = props[key] as? String ?: return null
        return v.ifBlank { null }
    }

    fun contains(key: String) = get(key) != null

    /** The Magisk version string (e.g. {@code 27.0}). */
    val version: String get() = get("version")!!
    /** The Magisk version code (integer). */
    val versionCode: Int get() = get("magisk.versionCode")!!.toInt()
    /** The stub APK version string. */
    val stubVersion: String get() = get("magisk.stubVersion")!!
    /** Comma-separated list of target ABIs. */
    val abiList: List<String> get() = get("abiList")!!.split(",")
}

/**
 * Resolves a file relative to the project root ({@code app/../}).
 * Returns the path unchanged if it is absolute.
 */
fun Project.rootFile(path: String): File {
    val file = File(path)
    return if (file.isAbsolute) file
    else File(rootProject.file(".."), path)
}

/**
 * Magisk Gradle plugin entry point.
 *
 * Loads configuration from Gradle properties, {@code config.prop}, and
 * {@code flags.prop}, and initializes the random generator for stub generation.
 */
class MagiskPlugin : Plugin<Project> {
    override fun apply(project: Project) = project.applyPlugin()

    private fun Project.applyPlugin() {
        initRandom(rootProject.file("dict.txt"))
        props.clear()

        // Load Gradle properties with magisk. prefix
        props.putAll(properties.filter { (key, _) -> key.startsWith("magisk.") })

        // Load config.prop (version, ABI list, etc.)
        val configPath: String? by this
        val configFile = rootFile(configPath ?: "config.prop")
        if (configFile.exists()) {
            configFile.inputStream().use {
                val config = Properties()
                config.load(it)
                props.putAll(config)
            }
        }

        // Load flags.prop, generated by build.py (build-time flags)
        val flagsProp = rootProject.layout.buildDirectory.file("flags.prop").get().asFile
        if (flagsProp.exists()) {
            flagsProp.inputStream().use {
                val flags = Properties()
                flags.load(it)
                props.putAll(flags)
            }
        }
    }
}
