/**
 * Activity that displays crash reports generated by [CrashHandler].
 *
 * Offers buttons to copy the report to the clipboard, share it via
 * other apps, or restart the application. Marked with [UntrackedActivity]
 * so [AppContext] does not track it as the foreground activity.
 */
package pro.magisk.core.base

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import android.widget.Toast
import androidx.activity.ComponentActivity
import pro.magisk.core.R
import pro.magisk.core.AppContext
import pro.magisk.core.utils.CrashHandler
import java.io.File

class DebugActivity : ComponentActivity(), UntrackedActivity {

    override fun onCreate(saved_instance_state: Bundle?) {
        super.onCreate(saved_instance_state)
        setContentView(R.layout.activity_debug)

        val crash_file = File(cacheDir, "crash_reports/crash_info.txt")
        val crash_info = if (crash_file.exists()) crash_file.readText() else "No crash info available."

        findViewById<TextView>(R.id.crash_info).text = crash_info
        findViewById<TextView>(R.id.crash_timestamp).text = crash_file
            .takeIf { it.exists() }
            ?.lastModified()
            ?.let { java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.US).format(java.util.Date(it)) }
            ?: ""

        findViewById<Button>(R.id.btn_copy).setOnClickListener {
            val clipboard = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
            clipboard.setPrimaryClip(ClipData.newPlainText("crash", crash_info))
            Toast.makeText(this, "Copied to clipboard", Toast.LENGTH_SHORT).show()
        }

        findViewById<Button>(R.id.btn_share).setOnClickListener {
            val share = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, crash_info)
            }
            startActivity(Intent.createChooser(share, "Share crash report"))
        }

        findViewById<Button>(R.id.btn_restart).setOnClickListener {
            crash_file.delete()
            val intent = packageManager.getLaunchIntentForPackage(packageName)
            if (intent != null) {
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK)
                startActivity(intent)
            }
            finish()
            Runtime.getRuntime().exit(0)
        }
    }
}
