name: Build MagiskT

on:
    push:
        branches: [native, native_test]
    pull_request:
        branches: [native, native_test]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        permissions: write-all

        strategy:
            matrix:
                build_type: [debug, release]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 1

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y ccache python3 python3-pip gh

            - name: Cache pip
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      pip-${{ runner.os }}-

            - name: Setup ccache
              run: |
                  mkdir -p ~/.ccache
                  echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
                  echo "CCACHE_MAXSIZE=3G" >> $GITHUB_ENV
                  echo "/usr/lib/ccache" >> $GITHUB_PATH
                  ccache --max-size=3G

            - name: Cache ccache
              uses: actions/cache@v4
              with:
                  path: ~/.ccache
                  key: ccache-${{ runner.os }}-${{ hashFiles('**/*.c','**/*.cpp','**/*.h') }}
                  restore-keys: |
                      ccache-${{ runner.os }}-

            - name: Cache Gradle
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
                  restore-keys: |
                      gradle-${{ runner.os }}-

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17
                  cache: gradle

            - name: Setup environment
              uses: ./.github/actions/setup
              with:
                  is-asset-build: true

            - name: Replace version
              run: |
                  if [ "${{ matrix.build_type }}" = "release" ]; then
                      sed -i 's/^version=.*/version=Modified/' config.prop
                  else
                      sed -i 's/^version=.*/version=Modified:D/' config.prop
                  fi

            - name: Build native libs
              run: |
                  if [ "${{ matrix.build_type }}" = "release" ]; then
                      python build.py -vr all
                  else
                      python build.py -v all
                  fi
                  
            - name: Clean and rename native libraries
              run: |
                  for dir in native/out/*; do
                      if [ -d "$dir" ]; then
                          find "$dir" -type f -name "*.a" -delete

                          for file in "$dir"/*; do
                              filename=$(basename "$file")

                              if [[ -f "$file" && ! "$filename" == lib*.so ]]; then
                                  mv "$file" "$dir/lib${filename}.so"
                              fi
                          done
                      fi
                  done

            - name: Create native zip
              run: |
                  cd native/out

                  zip_name="native_libs.zip"

                  zip -r "../../$zip_name" \
                      arm64-v8a \
                      armeabi-v7a \
                      x86 \
                      x86_64

                  echo "ZIP_NAME=$zip_name" >> $GITHUB_ENV

            - name: Upload native (${{ matrix.build_type }})
              uses: actions/upload-artifact@v4
              with:
                  name: native_${{ matrix.build_type }}
                  path: ${{ env.ZIP_NAME }}
                  compression-level: 0

            - name: Create GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  if [ "${{ matrix.build_type }}" = "release" ]; then
                      tag="native_r"
                  else
                      tag="native_d"
                  fi

                  commit=$(git rev-parse --short HEAD)
                  branch=${GITHUB_REF#refs/heads/}
                  build_time=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

                  sha256=$(sha256sum "${{ env.ZIP_NAME }}" | awk '{print $1}')

                  gh release delete "$tag" -y || true
                  git tag -d "$tag" || true
                  git push origin :refs/tags/$tag || true

                  git tag "$tag"
                  git push origin "$tag"

                  gh release create "$tag" "${{ env.ZIP_NAME }}" \
                      --title "Native Build;" \
                      --notes "SHA-256: $sha256"